### ISSUE TITLE
Ignore Alpha versions

### ISSUE THREAD

**Issue by fras2560** [thenativeweb/get-next-version#133]
### What is this feature about?
Currently using vx.y.z-alpha to denote dev builds. This causing issues in a different couple of ways. I want a flag that will ignore any tags ending in -alpha when determining the next version.
…

### What needs to be done to implement this feature?

- [ ] …
- [ ] …
- [ ] …

### What else should we know?

…

**Comment by fras2560** [comment]
Thinking something along these lines - https://github.com/thenativeweb/get-next-version/pull/134

NOTE: I am not a go programmer and just assembled this code for a demonstration of what this feature should do.

**Comment by fras2560** [comment]
Additionally might be helpful to have a filter for things that contain only -alpha as well

**Comment by goloroden** [comment]
Thanks for your suggestion.

However, we won't implement this. The reason for this is that there is no way to generate an `-alpha`, `-beta` or similar version number using this project, but only version numbers that follow the `x.y.z` schema.

Hence if you use this project from the start in your repository, you will never have these version numbers, so there is no need to filter them out.

If you introduce this project at a later point in time, and such version numbers already exist, it's up to you to clean this up once by manually setting a new version number that follows the expected schema. and then everything works as expected.

Since we don't plan to support generating these additional types of version numbers, we are also not going to implement detection of them.

**Comment by fras2560** [comment]
You should really add to the readme this limitation. From my perspective it should ignore them based upon what you said. Seems weird to care about versions that you cannot create.
