### ISSUE TITLE
Local time nor format respected

### ISSUE THREAD

**Issue by mrkskwsnck** [thenativeweb/get-next-version#35]
Version: 2.0.0
System: linux-amd64

It seems to me, as if the logger time is UTC, only?

```
user@host:~$ date && get-next-version 
Mi 27. Jul 15:14:08 CEST 2022
1:14PM FTL repository does not exist
```

It should respect local time zone (`TZ='Europe/Berlin'`) and format (`LC_TIME=de_DE.UTF-8`), IMHO.

**Comment by goloroden** [comment]
@mrkskwsnck Thanks for your suggestion – I'll get back to you soon regarding this issue.

**Comment by goloroden** [comment]
We discussed this internally, and we decided to stay with UTC since it avoids ambiguity, and thus helps to avoid misunderstandings.

Generally speaking, when showing time to the end user, we're with you, that the local time zone should be respected, but in this case we're addressing developers who are probably familiar with the concept of UTC, and so we think that the advantages outweigh the disadvantages.

Hence I'm going to close this one.
